task:
  osx_instance:
    image: mojave-flutter
  pub_cache:
    folder: ~/.pub-cache
  env:
    matrix:
      CHANNEL: "master"
      CHANNEL: "dev"
      CHANNEL: "beta"
      CHANNEL: "stable"
  setup_script:
    - pod repo update
    - flutter channel $CHANNEL
    - flutter upgrade
  create_simulator_script:
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-13-2 | xargs xcrun simctl boot
  build_script: 
    - flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=lib/main.dart --release --ios-arch=arm64,armv7
  test_script: flutter test
